local path = "Interface\\AddOns\\nMedia\\sounds\\"
local LSM = LibStub("LibSharedMedia-3.0", true)
if not LSM then return end
LSM:Register("sound", "1", path.."1.ogg")
LSM:Register("sound", "10", path.."10.ogg")
LSM:Register("sound", "2", path.."2.ogg")
LSM:Register("sound", "3", path.."3.ogg")
LSM:Register("sound", "4", path.."4.ogg")
LSM:Register("sound", "5", path.."5.ogg")
LSM:Register("sound", "6", path.."6.ogg")
LSM:Register("sound", "7", path.."7.ogg")
LSM:Register("sound", "8", path.."8.ogg")
LSM:Register("sound", "9", path.."9.ogg")
LSM:Register("sound", "Add", path.."Add.ogg")
LSM:Register("sound", "Adds", path.."Adds.ogg")
LSM:Register("sound", "Avoid", path.."Avoid.ogg")
LSM:Register("sound", "Bait", path.."Bait.ogg")
LSM:Register("sound", "Beam", path.."Beam.ogg")
LSM:Register("sound", "Bloodlust", path.."Bloodlust.ogg")
LSM:Register("sound", "Bomb", path.."Bomb.ogg")
LSM:Register("sound", "CC", path.."CC.ogg")
LSM:Register("sound", "Chain", path.."Chain.ogg")
LSM:Register("sound", "Clear", path.."Clear.ogg")
LSM:Register("sound", "Collect", path.."Collect.ogg")
LSM:Register("sound", "Debuff", path.."Debuff.ogg")
LSM:Register("sound", "Diamond", path.."Diamond.ogg")
LSM:Register("sound", "Dispell", path.."Dispell.ogg")
LSM:Register("sound", "Dodge", path.."Dodge.ogg")
LSM:Register("sound", "Dont Move", path.."Dont Move.ogg")
LSM:Register("sound", "Escort", path.."Escort.ogg")
LSM:Register("sound", "Flame", path.."Flame.ogg")
LSM:Register("sound", "FleeOrDie", path.."FleeOrDie.ogg")
LSM:Register("sound", "Gate", path.."Gate.ogg")
LSM:Register("sound", "Gather", path.."Gather.ogg")
LSM:Register("sound", "Green Portal Active", path.."Green Portal Active.ogg")
LSM:Register("sound", "Green", path.."Green.ogg")
LSM:Register("sound", "Healcd", path.."Healcd.ogg")
LSM:Register("sound", "Healdebuff", path.."Healdebuff.ogg")
LSM:Register("sound", "Hide", path.."Hide.ogg")
LSM:Register("sound", "High Energy", path.."High Energy.ogg")
LSM:Register("sound", "Immunity", path.."Immunity.ogg")
LSM:Register("sound", "Interrupt", path.."Interrupt.ogg")
LSM:Register("sound", "Invisibility", path.."Invisibility.ogg")
LSM:Register("sound", "Left", path.."Left.ogg")
LSM:Register("sound", "Linked", path.."Linked.ogg")
LSM:Register("sound", "Melee", path.."Melee.ogg")
LSM:Register("sound", "Mines", path.."Mines.ogg")
LSM:Register("sound", "Moon", path.."Moon.ogg")
LSM:Register("sound", "Move", path.."Move.ogg")
LSM:Register("sound", "Next", path.."Next.ogg")
LSM:Register("sound", "Orb", path.."Orb.ogg")
LSM:Register("sound", "Overlap", path.."Overlap.ogg")
LSM:Register("sound", "PeasantWarcry", path.."PeasantWarcry.ogg")
LSM:Register("sound", "Pots", path.."Pots.ogg")
LSM:Register("sound", "Purple Portal Active", path.."Purple Portal Active.ogg")
LSM:Register("sound", "Range", path.."Range.ogg")
LSM:Register("sound", "Readycheck", path.."Readycheck.ogg")
LSM:Register("sound", "Red Portal Active", path.."Red Portal Active.ogg")
LSM:Register("sound", "Red", path.."Red.ogg")
LSM:Register("sound", "Right", path.."Right.ogg")
LSM:Register("sound", "Scatter", path.."Scatter.ogg")
LSM:Register("sound", "Selfcd", path.."Selfcd.ogg")
LSM:Register("sound", "Shadow", path.."Shadow.ogg")
LSM:Register("sound", "Soak", path.."Soak.ogg")
LSM:Register("sound", "Spellsteal", path.."Spellsteal.ogg")
LSM:Register("sound", "Spread", path.."Spread.ogg")
LSM:Register("sound", "Stack", path.."Stack.ogg")
LSM:Register("sound", "Switch Target", path.."Switch Target.ogg")
LSM:Register("sound", "Taunt", path.."Taunt.ogg")
LSM:Register("sound", "Transition", path.."Transition.ogg")
LSM:Register("sound", "Turn", path.."Turn.ogg")
LSM:Register("sound", "Undead_Danger", path.."Undead_Danger.ogg")
LSM:Register("sound", "Undead_Incomming", path.."Undead_Incomming.ogg")
LSM:Register("sound", "Undead_Move", path.."Undead_Move.ogg")
LSM:Register("sound", "Undead_TurnBack", path.."Undead_TurnBack.ogg")
LSM:Register("sound", "Yellow", path.."Yellow.ogg")
LSM:Register("sound", "YouAreMarked", path.."YouAreMarked.ogg")
